

##############################################

#                                            #

#        dnscrypt-proxy configuration        #

#                                            #

##############################################



## This is an example configuration file.

## You should adjust it to your needs, and save it as "dnscrypt-proxy.toml"

##

## Online documentation is available here: https://dnscrypt.info/doc







##################################

#         Global settings        #

##################################



## List of servers to use

##

## Servers from the "public-resolvers" source (see down below) can

## be viewed here: https://dnscrypt.info/public-servers

##

## If this line is commented, all registered servers matching the require_* filters

## will be used.

##

## The proxy will automatically pick the fastest, working servers from the list.

## Remove the leading # first to enable this; lines starting with # are ignored.



# server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']





## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.

## Note: When using systemd socket activation, choose an empty set (i.e. [] ).



listen_addresses = ['127.0.0.1:53', '[::1]:53']





## Maximum number of simultaneous client connections to accept



max_clients = 150





## Switch to a different system user after listening sockets have been created.

## Note (1): this feature is currently unsupported on Windows.

## Note (2): this feature is not compatible with systemd socket activation.

## Note (3): when using -pidfile, the PID file directory must be writable by the new user



# user_name = 'nobody'





## Require servers (from static + remote sources) to satisfy specific properties



# Use servers reachable over IPv4

ipv4_servers = true



# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity

ipv6_servers = false



# Use servers implementing the DNSCrypt protocol

dnscrypt_servers = true

